Data Manipulation and Analysis with Pandas

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a
wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract
insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data.csv')
##fetch the first five rows
df.head(5)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
df.tail(5)

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [5]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [6]:
##Handling missing Values
df.isnull().any(axis=1)

0    False
1    False
2    False
3    False
4     True
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [7]:
df.isnull().any()

Country      False
Age           True
Salary        True
Purchased    False
dtype: bool

In [8]:
df[df.isnull().any(axis=1)] #axis=1 -> row wise

   Country   Age   Salary Purchased
4  Germany  40.0      NaN       Yes
6    Spain   NaN  52000.0        No

In [9]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [10]:
df.fillna(0)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      0.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   0.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [11]:
### filling missing values with the mean of the column
df['Age_fillNA']=df['Age'].fillna(df['Age'].mean())
df

   Country   Age   Salary Purchased  Age_fillNA
0   France  44.0  72000.0        No   44.000000
1    Spain  27.0  48000.0       Yes   27.000000
2  Germany  30.0  54000.0        No   30.000000
3    Spain  38.0  61000.0        No   38.000000
4  Germany  40.0      NaN       Yes   40.000000
5   France  35.0  58000.0       Yes   35.000000
6    Spain   NaN  52000.0        No   38.777778
7   France  48.0  79000.0       Yes   48.000000
8  Germany  50.0  83000.0        No   50.000000
9   France  37.0  67000.0       Yes   37.000000

In [12]:
df.dtypes

Country        object
Age           float64
Salary        float64
Purchased      object
Age_fillNA    float64
dtype: object

In [13]:
##Rename columns
df=df.rename(columns={'Country':'state'})

In [14]:
df.head()

     state   Age   Salary Purchased  Age_fillNA
0   France  44.0  72000.0        No        44.0
1    Spain  27.0  48000.0       Yes        27.0
2  Germany  30.0  54000.0        No        30.0
3    Spain  38.0  61000.0        No        38.0
4  Germany  40.0      NaN       Yes        40.0

In [15]:
## change datatypes
df['Value_new']=df['Salary'].astype(float)
df.head()

     state   Age   Salary Purchased  Age_fillNA  Value_new
0   France  44.0  72000.0        No        44.0    72000.0
1    Spain  27.0  48000.0       Yes        27.0    48000.0
2  Germany  30.0  54000.0        No        30.0    54000.0
3    Spain  38.0  61000.0        No        38.0    61000.0
4  Germany  40.0      NaN       Yes        40.0        NaN

In [16]:
# df.drop('Value_newe',axis=1,inplace=True)         #axis1=column
# df

In [17]:
df.loc[1,'Salary'] = 48050.5

In [18]:
df

     state   Age   Salary Purchased  Age_fillNA  Value_new
0   France  44.0  72000.0        No   44.000000    72000.0
1    Spain  27.0  48050.5       Yes   27.000000    48000.0
2  Germany  30.0  54000.0        No   30.000000    54000.0
3    Spain  38.0  61000.0        No   38.000000    61000.0
4  Germany  40.0      NaN       Yes   40.000000        NaN
5   France  35.0  58000.0       Yes   35.000000    58000.0
6    Spain   NaN  52000.0        No   38.777778    52000.0
7   France  48.0  79000.0       Yes   48.000000    79000.0
8  Germany  50.0  83000.0        No   50.000000    83000.0
9   France  37.0  67000.0       Yes   37.000000    67000.0

In [19]:
#another method
df['Salary'] = df['Salary'].replace(58000, 50000)

In [20]:
df

     state   Age   Salary Purchased  Age_fillNA  Value_new
0   France  44.0  72000.0        No   44.000000    72000.0
1    Spain  27.0  48050.5       Yes   27.000000    48000.0
2  Germany  30.0  54000.0        No   30.000000    54000.0
3    Spain  38.0  61000.0        No   38.000000    61000.0
4  Germany  40.0      NaN       Yes   40.000000        NaN
5   France  35.0  50000.0       Yes   35.000000    58000.0
6    Spain   NaN  52000.0        No   38.777778    52000.0
7   France  48.0  79000.0       Yes   48.000000    79000.0
8  Germany  50.0  83000.0        No   50.000000    83000.0
9   France  37.0  67000.0       Yes   37.000000    67000.0

In [21]:
## change datatypes
df['Value_new'] = df['Salary'].fillna(df['Salary'].mean()).astype(int)
df.head()

     state   Age   Salary Purchased  Age_fillNA  Value_new
0   France  44.0  72000.0        No        44.0      72000
1    Spain  27.0  48050.5       Yes        27.0      48050
2  Germany  30.0  54000.0        No        30.0      54000
3    Spain  38.0  61000.0        No        38.0      61000
4  Germany  40.0      NaN       Yes        40.0      62894

In [22]:
df['New Value']=df['Salary'].apply(lambda x:x*2)
df.head()

     state   Age   Salary Purchased  Age_fillNA  Value_new  New Value
0   France  44.0  72000.0        No        44.0      72000   144000.0
1    Spain  27.0  48050.5       Yes        27.0      48050    96101.0
2  Germany  30.0  54000.0        No        30.0      54000   108000.0
3    Spain  38.0  61000.0        No        38.0      61000   122000.0
4  Germany  40.0      NaN       Yes        40.0      62894        NaN

In [23]:
## Data Aggregating and grouping
df.head()

     state   Age   Salary Purchased  Age_fillNA  Value_new  New Value
0   France  44.0  72000.0        No        44.0      72000   144000.0
1    Spain  27.0  48050.5       Yes        27.0      48050    96101.0
2  Germany  30.0  54000.0        No        30.0      54000   108000.0
3    Spain  38.0  61000.0        No        38.0      61000   122000.0
4  Germany  40.0      NaN       Yes        40.0      62894        NaN

In [24]:
grouped_mean=df.groupby('Purchased')['Salary'].mean()
print(grouped_mean)

Purchased
No     64400.000
Yes    61012.625
Name: Salary, dtype: float64

In [25]:
grouped_sum=df.groupby(['Purchased','state'])['Salary'].sum()
print(grouped_sum)

Purchased  state
No         France      72000.0
           Germany    137000.0
           Spain      113000.0
Yes        France     196000.0
           Germany         0.0
           Spain       48050.5
Name: Salary, dtype: float64

In [29]:
## aggregate multiple functions
grouped_agg=df.groupby('state')['Salary'].agg(['mean','sum','count'])
grouped_agg

            mean       sum  count
state
France   67000.0  268000.0      4
Germany  68500.0  137000.0      2
Spain    53683.5  161050.5      3

In [30]:
## Meging and joining dataframe
# Create sample Dataframes
df1 = pd.DataFrame({'key': ['A','B','C'], 'Value1': [1,2,3]})
df2 = pd.DataFrame({'key': ['A','B','D'], 'Value2': [4,5,6]})

In [31]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

In [32]:
df2

  key  Value2
0   A       4
1   B       5
2   D       6

In [34]:
## Merge dataframe on the 'Key' Columns'
pd.merge(df1,df2,on="key",how="inner")

  key  Value1  Value2
0   A       1       4
1   B       2       5

In [35]:
pd.merge(df1,df2,on="key",how="outer")

  key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [36]:
pd.merge(df1,df2,on="key",how="left")

  key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [37]:
pd.merge(df1,df2,on="key",how="right")

  key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6