Pandas-DataFrame And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It
provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object,
while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure
with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [1]:
# Series
## A pandas series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [3]:
## create  a series from dictionary
data = {'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [2]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [3]:
## Dataframe
## create a Dataframe from a dictionary of list

data = {
    'Name': ['Krish','John','Jack'],
    'Age': [25,30,45],
    'City': ['Bnaglore','New york', 'Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Bnaglore
1   John   30  New york
2   Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [4]:
import numpy as np
np.array(df)

array([['Krish', 25, 'Bnaglore'],
       ['John', 30, 'New york'],
       ['Jack', 45, 'Florida']], dtype=object)

In [11]:
## Create a dataframe from a list of dictionaries
data = [
    {'Name': 'Krish', 'Age':32,'City': 'Banglore'},
    {'Name': 'John', 'Age':34,'City': 'New york'},
    {'Name': 'Bappy', 'Age':22,'City': 'Florida'},
    {'Name': 'Jack', 'Age':32,'City': 'America'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   32  Banglore
1   John   34  New york
2  Bappy   22   Florida
3   Jack   32   America
<class 'pandas.core.frame.DataFrame'>

In [8]:
df= pd.read_csv('Sales_data.csv')
print(df.head())
df.head(5)

   Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum
2           10003  2024-01-03         Clothing         Levi's 501 Jeans
3           10004  2024-01-04            Books        The Da Vinci Code
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set

   Units Sold  Unit Price  Total Revenue         Region Payment Method
0           2      999.99        1999.98  North America    Credit Card
1           1      499.99         499.99         Europe         PayPal
2           3       69.99         209.97           Asia     Debit Card
3           4       15.99          63.96  North America    Credit Card
4           1       89.99          89.99         Europe         PayPal

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [6]:
df.tail()

    Name  Age      City
0  Krish   32  Bnaglore
1   John   34  Bnaglore
2  Bappy   22  Bnaglore
3   Jack   32  Bnaglore

In [12]:
### Accessing data from DataFrame
# data
df

    Name  Age      City
0  Krish   32  Banglore
1   John   34  New york
2  Bappy   22   Florida
3   Jack   32   America

In [13]:
df['Name']
# type(df['Name'])
# df['Name']

0    Krish
1     John
2    Bappy
3     Jack
Name: Name, dtype: object

In [14]:
# Syntax: df.loc[row_label, column_label]
df.loc[0]   #it returns the entire first row.

# df.loc[1, 'Name']      #Output:John

Name       Krish
Age           32
City    Banglore
Name: 0, dtype: object

In [ ]:
df.iloc[0][2] #row position 0, column position 2

C:\Users\Mahi\AppData\Local\Temp\ipykernel_21336\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Bnaglore'

In [15]:
## Accessing a specified element
df.at[1,'Age']

34

In [16]:
df.at[2,'Name']

'Bappy'

In [17]:
##Accessing a specified element using iat
df.iat[2,2]

'Florida'

In [18]:
## Data Manipulation with dataframe
df

    Name  Age      City
0  Krish   32  Banglore
1   John   34  New york
2  Bappy   22   Florida
3   Jack   32   America

In [29]:
##Adding a new column 
df['Salary']=[50000,60000,70000,80000]
df

    Name  Age      City  Salary
0  Krish   32  Banglore   50000
1   John   34  New york   60000
2  Bappy   22   Florida   70000
3   Jack   32   America   80000

In [30]:
##Remove a column
df.drop('Salary',axis=1,inplace=True)
#axis=0 → Rows
#axis=1 → Columns
#inplace will drop permanent

In [31]:
df

    Name  Age      City
0  Krish   32  Banglore
1   John   34  New york
2  Bappy   22   Florida
3   Jack   32   America

In [34]:
##Add age to the column
df['Age']=df['Age']+1
df

    Name  Age      City
0  Krish   33  Banglore
1   John   35  New york
2  Bappy   23   Florida
3   Jack   33   America

In [37]:
df.drop(0,inplace=True)

In [38]:
df

    Name  Age      City
1   John   35  New york
2  Bappy   23   Florida
3   Jack   33   America

In [39]:
df=pd.read_csv('sales_data.csv')
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [41]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

# Group by a column and perform an aggregation
grouped = df.groupby('Product Category')['Total Revenue'].mean()
print(grouped)

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000
Product Category
Beauty Products     65.54750
Books               46.54825
Clothing           203.22325
Electronics        874.56025
Home Appliances    466.15400
Sports             358.16300
Name: Total Revenue, dtype: float64

In [42]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000